on: push

name: Build Package

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build Package
              uses: ouuan/pkgbuild-action@master
              id: build-package
              with:
                path: linux-vfio
